### PR TITLE
Revert "[bot-automerge] pinocchio v2.9.1"

### PR DESCRIPTION
**Pull request by jcarpent**
Reverts conda-forge/pinocchio-feedstock#61

### CODE REVIEW

**Comment by traversaro** [comment]
I am afraid that even after this PR conda will install install pinocchio 2.9.1 as it is the newest version. I think the only way of avoiding that is either to eventually release a version with an higher version number, or mark 2.9.1 as broken in https://github.com/conda-forge/admin-requests#mark-packages-as-broken-on-conda-forge .

**Comment by wolfv** [comment]
If you want to remove the builds from anaconda.org you'll have to send a pr to the repodata patches feedstock iirc

**Comment by proyan** [comment]
@wolfv Thanks for your review.
The documentation at https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages mentions that 

> "Open a new PR [for marking a package as broken in @conda-forge/admin-requests]. Once merged, a bot will label all listed files as broken, thus effectively removing them from the channel."

and 

> If the only issue is in the package metadata, we can directly patch it using the repo data patches feedstock. Please make a PR there to add a patch. In order to ensure future versions have the required changes, you also need to change the recipe to reflect the metadata changes.

Could you please confirm that since we want to fix not just the metadata, but remove the contents of the pre-release as well, marking the package as broken should be enough?

**Comment by proyan** [comment]
Thanks @traversaro for the info about broken packages.

**Comment by jcarpent** [comment]
> If you want to remove the builds from anaconda.org you'll have to send a pr to the repodata patches feedstock iirc

@wolf Could you elaborate a bit more on the way to proceed exactly?
@proyan Could you handle it?

**Comment by jcarpent** [comment]
> If you want to remove the builds from anaconda.org you'll have to send a pr to the repodata patches feedstock iirc

@wolfv Could you elaborate a bit more on the way to proceed exactly?
@proyan Could you handle it?

Thanks a lot.

**Pull request closed without merging**
