### PR TITLE
update v2.6.19

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@conda-forge-admin, please rerender

**Comment by jcarpent** [comment]
@xhochy @traversaro I need your help understanding why the build is not passing for `linux_64_numpy1.21python3.9.____cpython`. Do you have any idea on this issue?

**Comment by traversaro** [comment]
> @xhochy @traversaro I need your help understanding why the build is not passing for `linux_64_numpy1.21python3.9.____cpython`. Do you have any idea on this issue?

No idea, it seems to segfault when it tries to load the environment. To debug, it may be helpful to enable artifact upload, so we can debug the segfault locally. This can be done by adding:
~~~
azure:
  store_build_artifacts: true
~~~

in conda-forge.yml file.

**Comment by jcarpent** [comment]
@conda-forge-admin, please rerender

**Comment by jcarpent** [comment]
@traversaro @xhochy Seems to work now by restarting the CI several times. Thanks for your help.

**Pull request merged**
